### ISSUE TITLE
Unhandled Exception: Exception: Exception: FormatException: Unexpected end of input (at character 1)

### ISSUE THREAD

**Issue by FNPCMDs** [oakromulo/flutter_persistent_queue#9]
Hi, when I use `pq.push(<String, dynamic>{'i': 1});` (for example), it throw:
```
E/flutter (26619): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Exception: Exception: FormatException: Unexpected end of input (at character 1)
E/flutter (26619):
E/flutter (26619): ^
E/flutter (26619):
E/flutter (26619): #0      PersistentQueue._defer.checkErrorState (package:flutter_persistent_queue/flutter_persistent_queue.dart:117)
E/flutter (26619): #1      PersistentQueue._defer (package:flutter_persistent_queue/flutter_persistent_queue.dart:121)
E/flutter (26619): #2      PersistentQueue.push (package:flutter_persistent_queue/flutter_persistent_queue.dart:105)
```

Can you fix that ? Thanks u!

**Comment by oakromulo** [comment]
@FNPCMDs is it still an issue?

**Comment by FNPCMDs** [comment]
> @FNPCMDs is it still an issue?

Sorry, old saved data returned that error. I just uninstalled the app and then reinstalled it.

**Comment by oakromulo** [comment]
@FNPCMDs okay, I'll be here in case anything else pops up!
